### PR TITLE
fix handling of multiple DKIM signatures

### PR DESCRIPTION
**Pull request by freswa**
Rspamd supports multiple signatures per message for compatilibty between key sizes and signature algorithms. Unfortunately rspamd sends
- a string array for multiple headers
- a string for a single header

So we have to use a dirty workaround here.

### CODE REVIEW

**Comment by whataboutpereira** [comment]
Can you share your Rspamd DKIM config to sign multiple headers? I'm curious to see what it spits out. :) So far I've failed to coax multiple headers out of it.
...
nvm, figured it out finally. :)

**Comment by whataboutpereira** [comment]
I did the same using an interface here, akin to the way we did the other headers:

https://github.com/whataboutpereira/filter-rspamd/commit/19b4fc907b033075c8a4821fa3e95a4e14ca8150

**Comment by freswa** [comment]
I just tried your approach and I get `rspamd: failed to decode JSON response`

**Comment by whataboutpereira** [comment]
Curious.

**Comment by freswa** [comment]
Could it be that the interface should actually be an `map[string]interface{}`? Seems like the docs I can find regarding dynamic json are suggesting that.

**Comment by whataboutpereira** [comment]
Did you get that with one or multiple signatures. I tested with 2 and 1 signatures. Will test more tomorrow.

**Comment by freswa** [comment]
Got that with 2 signatures.

**Comment by whataboutpereira** [comment]
`map[string]interface{}` should work for JSON objects with keys (like the auth headers).

**Comment by whataboutpereira** [comment]
Are you sure you didn't revert to master? I get that message only when I revert to master.
DKIMSig interface{} `json:"dkim-signature"` eats practically everything.

**Comment by freswa** [comment]
Indeed I checked out the wrong branch. Sorry. LGTM.

**Comment by whataboutpereira** [comment]
Oops. No worries! :) Gilles can decide what to do with us.

PR-d: https://github.com/poolpOrg/filter-rspamd/pull/24

**Comment by poolpOrg** [comment]
merged #24

**Pull request closed without merging**
