### PR TITLE
new attempt at rspamd http over unix socket.

### PR DESCRIPTION
**Pull request by shaohme**
unix socket usage working

pledge altered

added more logging

### CODE REVIEW

**Review by maybebyte — CHANGES_REQUESTED** [review]
Although I have zero knowledge of Go's specifics, is it possible this PR is doing too much at the same time? I see unrelated changes to logging, whitespace, new error handling, new variables, and so on. While I can't speak for anyone else, I think that may be part of the reason it hasn't been accepted yet (and why #30 hasn't been closed yet either). Since this is a PR about adding Unix socket functionality, can you limit it to only those changes so it's easier to review?

(Also, I made zero changes to your diff, I didn't realize GitHub would imply that I'd changed it)

**Comment by shaohme** [comment]
It could be doing too much. I think a bit more verbose logging is not
too much of a problem. We can leave it out if it is.

I would appreciate comments from repository owners on as to why it has
not been accepted yet. Otherwise, I'm fumbling in the dark.

Maybe they are just busy ... ?

**Comment by ArchangeGabriel** [comment]
> Maybe they are just busy ... ?

@poolpOrg mostly stopped working on anything opensmtpd related. That’s why he didn’t handle this. Might happen at some point, but unpredictable.

**Comment by poolpOrg** [comment]
sorry for the delay, as @ArchangeGabriel said, I don't work much on opensmtpd related stuff these days, so I can easily miss a notification unless I get a nudge like today :-)

**Comment by ArchangeGabriel** [comment]
Thanks @poolpOrg!

**Comment by ArchangeGabriel** [comment]
P.S.: Could you tag a new release with current master for distribution purposes?

**Comment by maybebyte** [comment]
@poolpOrg Pinging because I'm also wondering if you can tag a new release. I can test + send a diff to ports@openbsd.org afterward to update the port.

**Comment by poolpOrg** [comment]
Hello, sorry I'm very busy these days so I didn't spot your comment.

I'll take care of tagging this week-end while I do a sweep of review on my notifications

Gilles

**Comment by Al2Klimov** [comment]
Not sure what exactly you changed. But it works now on my system.

**Pull request merged**
