### PR TITLE
Use smtp_message from rspamd for rejected messages.

### PR DESCRIPTION
**Pull request by whataboutpereira**
Use the smtp_message supplied by rspamd for SMTP rejection messages.

### CODE REVIEW

**Comment by poolpOrg** [comment]
reads ok but can you provide an example of how I would test that it works ?

**Comment by whataboutpereira** [comment]
If rspamd greylists or rejects a message it outputs a rejection message (you can also set rejection messages for certain rule matches etc - https://rspamd.com/doc/modules/force_actions.html)

Greylisted (note the capitalized "Try again" from rspamd):

```
838802156d1f67f0 smtp connected address=192.168.1.3 host=hostname
838802156d1f67f0 smtp tls ciphers=TLSv1.3:TLS_AES_256_GCM_SHA384:256
838802156d1f67f0 smtp failed-command command="DATA" result="451 Try again later"
```

Same message retransmitted (that contains a forbidden attachment):

```
8388021d9ad1853b smtp connected address=192.168.1.3 host=hostname
8388021d9ad1853b smtp tls ciphers=TLSv1.3:TLS_AES_256_GCM_SHA384:256
8388021d9ad1853b smtp failed-command command="DATA" result="550 Rejected due to bad file extension in attachment"
```

**Comment by whataboutpereira** [comment]
> reads ok but can you provide an example of how I would test that it works ?

So to test you need to send yourself something that isn't accepted. :D

**Comment by poolpOrg** [comment]
very nice !

**Comment by whataboutpereira** [comment]
I just noticed we need to reset response in txReset.

Now I'm thinking it might be an idea to split the transaction variables into a separate struct to make it obvious which variables belong to session and which to transaction.

https://github.com/whataboutpereira/filter-rspamd/commit/66e26d7f34a921b31738f7469360714b0e21c407

**Comment by poolpOrg** [comment]
Yes this was what I wanted to doHowever if you could fix the bug before the refactor, I'd be able to merge it right away and prepare a releaseOn Sep 21, 2019 14:30, Reio Remma <notifications@github.com> wrote:I just noticed we need to reset response in txReset.
Now I'm thinking it might be an idea to split the transaction variables into a separate struct to make it obvious which variables belong to session and which to transaction.
whataboutpereira@66e26d7

**Comment by whataboutpereira** [comment]
Made a separate PR for it.

**Pull request merged**
