### PR TITLE
Add headers provided by add_headers field from Rspamd.

### PR DESCRIPTION
**Pull request by whataboutpereira**
Process add_headers/remove_headers that rspamd provides.

Headers (add_headers) come from rspamd in the format of either string or map { order: number, value: string }. The map format is for Authentication-Results.

I split the header writing code from DKIM header to a separate function to reuse the code.

### CODE REVIEW

**Comment by poolpOrg** [comment]
I'm sorry, this one makes me a bit nervous so close from release.

I will tag the filter-rspamd release then merge this after so I can test it for a while before we include it in a filter-rspamd release.

**Comment by whataboutpereira** [comment]
That's quite alright. :)

**Comment by poolpOrg** [comment]
Just to clarify, it's not necessarily related to the quality of your diff more than it is me being extra cautious and particularly with a project written in Go which is a new language to me. I don't know about interface{} yet so it's hard to me to know if the code is correct when I have zones of shadow in my understanding :-)

**Comment by whataboutpereira** [comment]
Well, it's the same for me concerning Go. :)

I also plan to test with ARC enabled soon, to see what that might throw up (pun almost intended).

**Comment by whataboutpereira** [comment]
One last thing for now - apparently underscores in variable names in Go are against the Go style (and I had a linter screaming at me because of it). Do you want me to make another pull request to change mail_from and rcpt_to to mailFrom and rcptTo to satisfy that?

**Comment by poolpOrg** [comment]
Yes, please

**Comment by whataboutpereira** [comment]
Okay, I think I messed this pull up by merging from master thinking it will trim the diff. ./

**Comment by poolpOrg** [comment]
haha

**Comment by whataboutpereira** [comment]
Aaaand... Voila. Today's lesson - force push. .) Have a nice weekend. :)

**Comment by whataboutpereira** [comment]
I made a separate pull request for header removal, so this one became simpler still. :)

ARC headers also work now.

**Comment by whataboutpereira** [comment]
Very nice, all is in now. :)

**Pull request merged**
