### PR TITLE
Unescape/escape leading dots when reading to/writing from smtpd.

### PR DESCRIPTION
**Pull request by whataboutpereira**
Unescape leading dots when reading raw SMTP input data and escape leading dots again when writing back to smtpd.

This fixes failing DKIM validation in Rspamd for mails that have any lines in them with a leading dot.

Line 178 - that I suspect was just an oddity. :)

### CODE REVIEW

**Comment by poolpOrg** [comment]
oh noes, line 178 wasn't an oddity and you just introduced a bug :-)

it is needed to correctly process data lines which contain | as the parsing will have split them into multiple fields.

other than that the diff is ok for me

**Comment by whataboutpereira** [comment]
Oh, duh. There's always something that escapes me! ;) Updated!

**Comment by poolpOrg** [comment]
better :-)

**Comment by whataboutpereira** [comment]
Wonderful. :)

**Pull request merged**
